### ISSUE TITLE
Import StubLibrary in RobotFramework failed

### ISSUE THREAD

**Issue by audreygersan** [ravihuang/robotframework-stublibrary#1]
Hi,

I try to import StubLibrary in RobotFramework's interface (RIDE) but the line stay red.

In the log i have : 
C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\St
ubLibrary\http_stub.py:6: MonkeyPatchWarning: Monkey-patching ssl after ssl has
already been imported may lead to errors, including RecursionError on Python 3.6
. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-
patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that ha
d direct imports (NOT patched): ['urllib3.contrib.pyopenssl (C:\\Users\\rcdq9206
\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\urllib3\\co
ntrib\\pyopenssl.py)'].
  monkey.patch_all(thread=False)  # make sure to do the monkey-patching before l
oading the falcon package!
FAILED StubLibrary Importing test library 'StubLibrary' failed: SyntaxError: inv
alid syntax (__init__.py, line 53)
Traceback (most recent call last):
  File "C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-pac
kages\robotide\lib\robot\utils\importer.py", line 153, in _import
    return __import__(name, fromlist=fromlist)
  File "C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-pac
kages\StubLibrary\__init__.py", line 19, in <module>
    from StubLibrary.http_stub import HTTP
  File "C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-pac
kages\StubLibrary\http_stub.py", line 9, in <module>
    import webtest
  File "C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-pac
kages\webtest\__init__.py", line 9, in <module>
    from webtest.app import TestApp
  File "C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-pac
kages\webtest\app.py", line 32, in <module>
    from webtest.response import TestResponse
  File "C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-pac
kages\webtest\response.py", line 5, in <module>
    from webtest import forms
  File "C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-pac
kages\webtest\forms.py", line 8, in <module>
    from bs4 import BeautifulSoup
PYTHONPATH:
  C:\Applications\Python27
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\python37.zip
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\DLLs
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
setuptools-41.0.0-py3.7.egg
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
pip-19.0.3-py3.7.egg
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
pubsub-0.1.2-py3.7.egg
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
fernet-1.0.1-py3.7.egg
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
pyopenssl-19.1.0.dev0-py3.7.egg
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
pyqc-0.4.4-py3.7.egg
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
robotide\spec
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
robotide\lib
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
robotide\contrib\testrunner\../../lib
  C:\Users\rcdq9206\AppData\Local\Programs\Python\Python37-32\lib\site-packages\
robotide\contrib\testrunner\../../lib

Can you help me ?

Thanks a lot

Audreygersan

**Comment by audreygersan** [comment]
I use 2to3 -w bs4 on BeautifulSoup and i update gevent on 1.5a1
i use this python command :
from gevent import monkey
monkey.patch_all()

It's works!

**Comment by ravihuang** [comment]
monkey.patch_all() command should be called before importing ssl, both
RequestsLibrary and StubLibrary will import ssl, if you use these two
libraries at the same time, make sure to import the StubLibrary first.

audreygersan <notifications@github.com> 于2019年7月30日周二 下午6:01写道：
